fix(core-cell): 修改填充背景颜色接口
iCloudWorkGroup/fengniao pull request #244
Opened 2017-06-06 06:24 UTC by CJL5678

移除多区域设置背景颜色功能

fixed #226

2017-06-06 08:39 UTC, wlchair requested changes

2017-06-06 08:39 UTC, wlchair commented on js/entrance/tool/setfillcolor.js
> +	var setFillColor = function(sheetId, color, label) {
1. label属于关键词
2. label在英语里，跟行、列的标号没有直接关系
换个符合的含义的单词来处理

2017-06-06 08:39 UTC, wlchair commented on js/entrance/tool/setfillcolor.js
>  'use strict';
之前在金浩然的浏览器里，出现了'use strcit'，不能被加载的情况，因为在最顶端使用这句话，他会检查requirejs，会拖慢整体的加载时间，同时还存在兼容性问题。

2017-06-06 08:39 UTC, wlchair commented on js/entrance/tool/setfillcolor.js
> +				sheetId: '1',
sheetid，不发送

2017-06-06 08:45 UTC, CJL5678 commented on js/entrance/tool/setfillcolor.js
> +				sheetId: '1',
sheetId 如果做修改的话，以后统一修改

2017-06-06 08:46 UTC, CJL5678 commented on js/entrance/tool/setfillcolor.js
> +	var setFillColor = function(sheetId, color, label) {
使用label表示标识的意思 
如果做修改的话，以后统一修改

2017-06-06 08:47 UTC, CJL5678 commented on js/entrance/tool/setfillcolor.js
>  'use strict';
以后统一移动到函数内部

2017-06-07 02:43 UTC, wlchair approved these changes

2017-06-07 02:43 UTC, merged