fix(core-row/col): 修改删除添加行列的对外接口
iCloudWorkGroup/fengniao pull request #245
Opened 2017-06-06 07:15 UTC by CJL5678

修改删除添加行列的对外接口

fixed #241

2017-06-06 08:29 UTC, wlchair requested changes

2017-06-06 08:29 UTC, wlchair commented on js/spreadsheet/excelbuild.js
> +			SpreadSheet.prototype.addCol = addCol.addCol.bind(addCol);
代码这么写？原因四什么？怎么理解这句话？`addRow.addRow.bind(addRow)`

2017-06-06 08:29 UTC, wlchair commented on js/entrance/tool/deletecol.js
> -			if (operRegion.endRowIndex === 'MAX') {
这段跟这次pull有关系？为什么要删除这段？

2017-06-06 08:56 UTC, CJL5678 commented on js/spreadsheet/excelbuild.js
> +			SpreadSheet.prototype.addCol = addCol.addCol.bind(addCol);
addRow是一个对象，内部包含addRow方法，向SpreadSheet原型对象添加addRow方法,使用bind修正addRow中的this指向addRow对象

2017-06-06 08:59 UTC, CJL5678 commented on js/entrance/tool/deletecol.js
> -			if (operRegion.endRowIndex === 'MAX') {
对于外部传入的区域，如果只传入行/列，不传入区域， 则默认为正行整列操作, endRowIndex/endColIndex解析为MAX，然后进行整行整列操作，插入/删除行列，也只传入行/列，但不做整行整列处理

2017-06-07 03:03 UTC, wlchair approved these changes

2017-06-07 03:03 UTC, merged